<?php

declare(strict_types=1);

namespace Drupal\stanford_migrate\Plugin\migrate\process;

use Drupal\Core\File\Event\FileUploadSanitizeNameEvent;
use Drupal\Core\File\FileSystemInterface;
use Drupal\migrate\MigrateExecutableInterface;
use Drupal\migrate\Plugin\migrate\process\Download;
use Drupal\migrate\Row;
use GuzzleHttp\ClientInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\EventDispatcher\EventDispatcher;

/**
 * Extends the download plugin, adding filename transliteration.
 */
class StanfordDownload extends Download {

  /**
   * {@inheritDoc}
   */
  public static function create(ContainerInterface $container, array $configuration, $plugin_id, $plugin_definition) {
    return new static(
      $configuration,
      $plugin_id,
      $plugin_definition,
      $container->get('file_system'),
      $container->get('http_client'),
      $container->get('event_dispatcher')
    );
  }

  /**
   * {@inheritDoc}
   */
  public function __construct(array $configuration, $plugin_id, array $plugin_definition, FileSystemInterface $file_system, ClientInterface $http_client, protected EventDispatcher $eventDispatcher) {
    parent::__construct($configuration, $plugin_id, $plugin_definition, $file_system, $http_client);
  }

  /**
   * {@inheritDoc}
   */
  public function transform($value, MigrateExecutableInterface $migrate_executable, Row $row, $destination_property) {
    // Copies the stub behavior of the parent plugin.
    if ($row->isStub()) {
      return NULL;
    }
    [$source, $destination] = $value;
    $filename = basename($destination);

    $event = new FileUploadSanitizeNameEvent($filename, '');
    $this->eventDispatcher->dispatch($event);

    $destination = str_replace($filename, $event->getFilename(), $destination);
    $value = [$source, $destination];

    return parent::transform($value, $migrate_executable, $row, $destination_property); // TODO: Change the autogenerated stub
  }

}
