<?php

/**
 * @file
 * stanford_migrate.install
 */

/**
 * Install readonly_field_widget module.
 */
function stanford_migrate_update_8001() {
  \Drupal::service('module_installer')->install(['readonly_field_widget']);
}

/**
 * Install empty_field module.
 */
function stanford_migrate_update_8002() {
  \Drupal::service('module_installer')->install(['empty_fields']);
}

/**
 * Set the default debug_mode setting explicitly.
 */
function stanford_migrate_update_8003() {
  \Drupal::configFactory()
    ->getEditable('stanford_migrate.settings')
    ->set('debug_mode', FALSE)
    ->save();
}
