<?php

/**
 * @file
 * Contains stanford_migrate.module.
 */

use Drupal\Core\Cache\Cache;
use Drupal\ultimate_cron\CronJobInterface;
use Drupal\Core\Site\Settings;

/**
 * Migration callback to just get the current timestamp.
 *
 * We use this function in migration callback processes because using `time` as
 * the callback produces messages about "function accepts 0 arguments, 1
 * argument passed". So we just have our own callback that takes the argument
 * from the migration process and does nothing with it.
 *
 * @param mixed $arg
 *   Passed parameter from migration plugin `callback`.
 *
 * @return int
 *   Current timestamp.
 *
 * @see \Drupal\migrate\Plugin\migrate\process\Callback::transform()
 */
function _stanford_migrate_get_time($arg = NULL) {
  return time();
}

/**
 * Ultimate cron callback function to execute a migration group.
 *
 * The entity id should be in the form `stanford_migrate_{migrate_group_id}` to
 * execute that group.
 *
 * @param \Drupal\ultimate_cron\CronJobInterface $cron_entity
 *   Ultimate cron entity.
 */
function stanford_migrate_ultimate_cron_task(CronJobInterface $cron_entity) {
  $migrate_settings = \Drupal::config('stanford_migrate.settings');

  // Invalidate migration plugins to gather any changes to config entities
  // before running import. This allows for any changes to the source urls.
  \Drupal::service('plugin.manager.migration')->clearCachedDefinitions();
  Cache::invalidateTags(['migration_plugins']);

  /** @var \Drupal\stanford_migrate\StanfordMigrateInterface $migrate_service */
  $migrate_service = \Drupal::service('stanford_migrate');
  $migrations = $migrate_service->getMigrationList();

  $migration_group = str_replace('stanford_migrate_', '', $cron_entity->id());
  // Execute the migration entities in the provided migration group.
  if ($migration_group && !empty($migrations[$migration_group])) {

    $migrate_options = $migrate_settings->get('cron_options.' . $migration_group) ?: [];
    $migrate_options += $migrate_settings->get('cron_options.default') ?: [];

    return array_walk($migrations[$migration_group], [
      $migrate_service,
      'executeMigration',
    ], $migrate_options);
  }
  \Drupal::logger('stanford_migrate')
    ->info('No migration group @group exists. No migration executed.', ['@group' => $migration_group]);
}
