name: Lint Code Base
on:
  push:
    branches-ignore: [master, main]
  pull_request:
    branches: [master, main]
jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP Action
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: imagick
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
      - name: Composer Install
        run: composer install -n
      - name: Lint Code Base
        uses: github/super-linter/slim@v4
        env:
          # Change to false to only validate changed files.
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_PHP_PSALM: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILTER_REGEX_EXCLUDE: 'tests.*'
